//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Clients = new HashSet<Client>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string HearAboutUs { get; set; }
        public Nullable<long> ReceivedServicesInPast { get; set; }
        public string PregnancyStatus { get; set; }
        public Nullable<long> BabyBornAlready { get; set; }
        public Nullable<long> NotPregHaveMoreOneKid { get; set; }
        public string PregnancyTestResults { get; set; }
        public Nullable<long> ContactAfterToday { get; set; }
        public string StaffConducting { get; set; }
        public string DistributionOfItems { get; set; }
        public string FollowUpCallDate { get; set; }
        public Nullable<long> FollowUpCall { get; set; }
        public string ClientParticipationStatus { get; set; }
        public string ApplicationDate { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
