//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFreshStart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientFreshStart()
        {
            this.SupportGroups = new HashSet<SupportGroup>();
        }
    
        public long Id { get; set; }
        public long FreshStartId { get; set; }
        public long ClientId { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual FreshStart FreshStart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportGroup> SupportGroups { get; set; }
    }
}
