//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProgramCurriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientProgramCurriculum()
        {
            this.ClientProgramCurriculumAttributes = new HashSet<ClientProgramCurriculumAttribute>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> ProgramCurriculumId { get; set; }
        public string NoActivityInYear { get; set; }
        public string BecameActiveInYear { get; set; }
        public string StillActiveEOY { get; set; }
        public string GraceEOY { get; set; }
        public string SignUpDate { get; set; }
        public string MP { get; set; }
        public string PP { get; set; }
        public string DueDate { get; set; }
        public string HealthyDelivery { get; set; }
        public string ContinuedWithMotherhood { get; set; }
        public string BirthComplicationsIssues { get; set; }
        public string LeftProgramBeforeBirth { get; set; }
        public string Expecting { get; set; }
        public string ContinuedWithMP { get; set; }
        public string Reward { get; set; }
    
        public virtual ProgramCurriculum ProgramCurriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramCurriculumAttribute> ClientProgramCurriculumAttributes { get; set; }
        public virtual Client Client { get; set; }
    }
}
