//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClassAttendances = new HashSet<ClassAttendance>();
            this.ClientFreshStarts = new HashSet<ClientFreshStart>();
            this.Pregnancies = new HashSet<Pregnancy>();
            this.PregnancyStatus = new HashSet<PregnancyStatu>();
            this.ProgressPointTrackings = new HashSet<ProgressPointTracking>();
            this.RelativeFreshStarts = new HashSet<RelativeFreshStart>();
            this.ServiceInfoes = new HashSet<ServiceInfo>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CurrentStatus { get; set; }
        public string ApplicationDate { get; set; }
        public string ActiveInactiveStatus { get; set; }
        public string ZipCode { get; set; }
        public string MaritalStatus { get; set; }
        public string AgeRange { get; set; }
        public string Ethnicity { get; set; }
        public string CurrentStudentEnrollment { get; set; }
        public string EducationalBackground { get; set; }
        public string Smoker { get; set; }
        public Nullable<long> ProgressPoints { get; set; }
        public Nullable<long> ContinuedFromPrevYears { get; set; }
        public Nullable<long> NewThisYear { get; set; }
        public Nullable<long> MotherhoodProgram { get; set; }
        public Nullable<long> ParentingProgram { get; set; }
        public Nullable<long> NoActivityNewYear { get; set; }
        public Nullable<long> BecameInactive { get; set; }
        public Nullable<long> LeftProgramBeforeBirth { get; set; }
        public Nullable<long> StillActiveYE { get; set; }
        public Nullable<long> GracePeriod { get; set; }
        public string Comment { get; set; }
        public Nullable<long> ReturnNewPregnancy { get; set; }
        public string RegisteringIndividual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAttendance> ClassAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFreshStart> ClientFreshStarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregnancy> Pregnancies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PregnancyStatu> PregnancyStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgressPointTracking> ProgressPointTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelativeFreshStart> RelativeFreshStarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceInfo> ServiceInfoes { get; set; }
    }
}
