//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public long Id { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> Status { get; set; }
        public string Location { get; set; }
        public string HoursPerWeek { get; set; }
        public string MakingLivableWage { get; set; }
        public string Comment { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
