//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Father
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Father()
        {
            this.ClientFathers = new HashSet<ClientFather>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string BirthDate { get; set; }
        public string WorkingStatus { get; set; }
        public string WorkLocation { get; set; }
        public string SchoolStatus { get; set; }
        public string SchoolName { get; set; }
        public Nullable<long> SupportiveStatus { get; set; }
        public string IfBFinPicture { get; set; }
        public string IFBFfatherOfKids { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientFather> ClientFathers { get; set; }
    }
}
