//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emergency> Emergencies { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<ClassAttendance> ClassAttendances { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientFreshStart> ClientFreshStarts { get; set; }
        public virtual DbSet<FreshStart> FreshStarts { get; set; }
        public virtual DbSet<ItemRequested> ItemRequesteds { get; set; }
        public virtual DbSet<Pregnancy> Pregnancies { get; set; }
        public virtual DbSet<ProgressPointTracking> ProgressPointTrackings { get; set; }
        public virtual DbSet<RelativeFreshStart> RelativeFreshStarts { get; set; }
        public virtual DbSet<ServiceInfo> ServiceInfoes { get; set; }
        public virtual DbSet<ServiceRequested> ServiceRequesteds { get; set; }
        public virtual DbSet<SupportGroup> SupportGroups { get; set; }
    }
}
