//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramCurriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramCurriculum()
        {
            this.ClientProgramCurriculums = new HashSet<ClientProgramCurriculum>();
            this.ProgramCurriculumAttributes = new HashSet<ProgramCurriculumAttribute>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ProgramId { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Attended { get; set; }
    
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProgramCurriculum> ClientProgramCurriculums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramCurriculumAttribute> ProgramCurriculumAttributes { get; set; }
    }
}
