//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace se2_loon_hh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceInfo()
        {
            this.ItemRequesteds = new HashSet<ItemRequested>();
            this.ServiceRequesteds = new HashSet<ServiceRequested>();
        }
    
        public long Id { get; set; }
        public long ClientId { get; set; }
        public Nullable<long> NewContact { get; set; }
        public Nullable<long> NewWalkIn { get; set; }
        public Nullable<long> WalkIn { get; set; }
        public Nullable<long> PhoneCenterHrs { get; set; }
        public Nullable<long> PhoneAfterHrs { get; set; }
        public Nullable<long> PrankCall { get; set; }
        public Nullable<long> Email { get; set; }
        public Nullable<long> OffSite { get; set; }
        public Nullable<long> OutgoingCallMailEmail { get; set; }
        public Nullable<long> RepBySomeoneElse { get; set; }
        public string Date { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequested> ItemRequesteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequested> ServiceRequesteds { get; set; }
    }
}
